[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "divvy-demand"
version = "0.1.0"
dependencies = [
    "boto3",
    "pandas",
    "pyarrow",
    "requests",
    "python-dotenv",
    "matplotlib",
    "seaborn",
    "statsmodels",
    "scipy",
]

[tool.setuptools.packages.find]
where = ["src"]
